version: 2.1

orbs:
  android: circleci/android@2.3.0
  gcp-cli: circleci/gcp-cli@2.2.0

jobs:
  unit-test:
    executor:
      name: android/android-machine
      resource-class: xlarge
      tag: 2023.04.1
    steps:
      - checkout
      - android/create-avd:
          avd-name: myavd
          system-image: system-images;android-29;default;x86
          install: true
      - android/start-emulator:
          avd-name: myavd
          no-window: true
          post-emulator-launch-assemble-command: ""
          restore-gradle-cache-prefix: v1a
      - android/run-tests:
          test-command: chmod 777 ./test.sh && ./test.sh
      - android/save-gradle-cache
      - android/save-build-cache
      - run: cd ./project/app/build/test-results && ls -al
      - run:
          name: Save test results
          command: |
              mkdir -p ~/test-results/junit/
              find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/junit
          
workflows:
  test-and-build:
    jobs:
      - unit-test

